server:
  port: 8080
  log_level: "info"

email:
  - provider: "gmail"
    username: "your-email@gmail.com"
    password: "your-app-password"  # Use app-specific password for Gmail
    imap_server: "imap.gmail.com"
    imap_port: 993
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true

  # Example for generic IMAP/SMTP
  # - provider: "generic"
  #   username: "user@example.com"
  #   password: "your-password"
  #   imap_server: "mail.example.com"
  #   imap_port: 993
  #   smtp_server: "mail.example.com"
  #   smtp_port: 587
  #   use_tls: true